### ISSUE TITLE
Automatic bootimage

### ISSUE THREAD

**Issue by PascalSchwab** [LauchOS/LauchOS#8]
Github Actions: After pushing on the main-branch it should create a new bootimage and save it as package.

**Comment by 65Juko** [comment]
@PascalSchwab upload vom bootimage wird mitm 403 denied, maybe repo settings?
![grafik](https://github.com/LauchOS/LauchOS/assets/75746485/cdceeb0e-9dba-4c80-a772-f0255f45a7e1)
https://github.com/LauchOS/LauchOS/actions/runs/5650645595/job/15307370632
